### PR TITLE
Adds 2 Columns - Comment Status and Created Date

### PR DESCRIPTION
**Pull request by kyledodge**
This plugin has been a huge time saver, so thank you for creating it! Some pain points I have found is not knowing how old a PR is and if any comments on the PR have been resolved yet. This PR adds a column for the created date to quickly see how old a PR is, formatted with MomentJS. It also adds a column to show comments resolved out of total comments - if no comments exist the column is blank. This has been tested in my personal devops instance.
pr-update

### CODE REVIEW

**Comment by nshenoy** [comment]
Thanks for the kind words. And thanks for this feature - great idea! I'll take a look at these soon. Was this tested on IE and Edge as well as Chrome? Looks like we have a number of people using older browsers. Thanks!

**Comment by kyledodge** [comment]
> Thanks for the kind words. And thanks for this feature - great idea! I'll take a look at these soon. Was this tested on IE and Edge as well as Chrome? Looks like we have a number of people using older browsers. Thanks!

Yes, tested with Edge, IE, Chrome and Safari and confirmed it works. Sorry - I should have mentioned that in the PR

**Comment by nshenoy** [comment]
So sorry to do this for you, but we have some nasty merge conflicts now. :( We just merged a PR that upgraded the SDK which resulted in a number of changes, including moving to Typescript 3.5.1. Would it be possible to reimplement these changes on the new code base?

**Comment by kyledodge** [comment]
> So sorry to do this for you, but we have some nasty merge conflicts now. :( We just merged a PR that upgraded the SDK which resulted in a number of changes, including moving to Typescript 3.5.1. Would it be possible to reimplement these changes on the new code base?

I just noticed that - no worries, I'll work on implementing it on the new code base

**Pull request closed without merging**
